// Vehicle Makes and Models
export const vehicleMakes = [
	"Acura",
	"Alfa Romeo",
	"Aston Martin",
	"Audi",
	"Bentley",
	"BMW",
	"Buick",
	"Cadillac",
	"Chevrolet",
	"Chrysler",
	"Dodge",
	"Ferrari",
	"Fiat",
	"Ford",
	"Genesis",
	"GMC",
	"Honda",
	"Hyundai",
	"Infiniti",
	"Jaguar",
	"Jeep",
	"Kia",
	"Lamborghini",
	"Land Rover",
	"Lexus",
	"Lincoln",
	"Maserati",
	"Mazda",
	"McLaren",
	"Mercedes-Benz",
	"Mini",
	"Mitsubishi",
	"Nissan",
	"Porsche",
	"Ram",
	"Rolls-Royce",
	"Subaru",
	"Tesla",
	"Toyota",
	"Volkswagen",
	"Volvo",
];

// Models by Make
export const vehicleModelsByMake: Record<string, string[]> = {
	Acura: ["ILX", "MDX", "NSX", "RDX", "TLX"],
	"Alfa Romeo": ["4C", "Giulia", "Stelvio"],
	"Aston Martin": ["DB11", "DBS", "Vantage"],
	Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "Q3", "Q5", "Q7", "Q8", "R8", "RS", "S4", "S5", "TT"],
	Bentley: ["Bentayga", "Continental", "Flying Spur"],
	BMW: [
		"1 Series",
		"2 Series",
		"3 Series",
		"4 Series",
		"5 Series",
		"6 Series",
		"7 Series",
		"8 Series",
		"i3",
		"i8",
		"M2",
		"M3",
		"M4",
		"M5",
		"X1",
		"X2",
		"X3",
		"X4",
		"X5",
		"X6",
		"X7",
		"Z4",
	],
	Buick: ["Enclave", "Encore", "Envision", "LaCrosse", "Regal"],
	Cadillac: ["ATS", "CT4", "CT5", "CT6", "CTS", "Escalade", "XT4", "XT5", "XT6"],
	Chevrolet: [
		"Blazer",
		"Bolt",
		"Camaro",
		"Colorado",
		"Corvette",
		"Cruze",
		"Equinox",
		"Impala",
		"Malibu",
		"Silverado",
		"Spark",
		"Suburban",
		"Tahoe",
		"Trailblazer",
		"Traverse",
		"Trax",
	],
	Chrysler: ["300", "Pacifica", "Voyager"],
	Dodge: ["Challenger", "Charger", "Durango", "Grand Caravan", "Journey"],
	Ferrari: ["488", "812", "F8", "GTC4", "Portofino", "Roma", "SF90"],
	Fiat: ["124 Spider", "500", "500L", "500X"],
	Ford: [
		"Bronco",
		"EcoSport",
		"Edge",
		"Escape",
		"Expedition",
		"Explorer",
		"F-150",
		"F-250",
		"F-350",
		"Fiesta",
		"Focus",
		"Fusion",
		"Mustang",
		"Ranger",
		"Transit",
	],
	Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
	GMC: ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
	Honda: ["Accord", "Civic", "CR-V", "Fit", "HR-V", "Insight", "Odyssey", "Passport", "Pilot", "Ridgeline"],
	Hyundai: ["Accent", "Elantra", "Ioniq", "Kona", "Palisade", "Santa Fe", "Sonata", "Tucson", "Veloster", "Venue"],
	Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
	Jaguar: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF", "XJ"],
	Jeep: ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
	Kia: [
		"Cadenza",
		"Forte",
		"K5",
		"Niro",
		"Optima",
		"Rio",
		"Sedona",
		"Seltos",
		"Sorento",
		"Soul",
		"Sportage",
		"Stinger",
		"Telluride",
	],
	Lamborghini: ["Aventador", "Huracan", "Urus"],
	"Land Rover": [
		"Defender",
		"Discovery",
		"Range Rover",
		"Range Rover Evoque",
		"Range Rover Sport",
		"Range Rover Velar",
	],
	Lexus: ["ES", "GS", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "UX"],
	Lincoln: ["Aviator", "Continental", "Corsair", "MKZ", "Nautilus", "Navigator"],
	Maserati: ["Ghibli", "Levante", "Quattroporte"],
	Mazda: ["CX-3", "CX-30", "CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
	McLaren: ["570S", "600LT", "720S", "Artura", "GT"],
	"Mercedes-Benz": [
		"A-Class",
		"AMG GT",
		"C-Class",
		"CLA",
		"CLS",
		"E-Class",
		"G-Class",
		"GLA",
		"GLB",
		"GLC",
		"GLE",
		"GLS",
		"S-Class",
		"SL",
		"SLC",
	],
	Mini: ["Clubman", "Convertible", "Countryman", "Hardtop"],
	Mitsubishi: ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
	Nissan: [
		"Altima",
		"Armada",
		"Frontier",
		"GT-R",
		"Kicks",
		"Leaf",
		"Maxima",
		"Murano",
		"Pathfinder",
		"Rogue",
		"Sentra",
		"Titan",
		"Versa",
	],
	Porsche: ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
	Ram: ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
	"Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Wraith"],
	Subaru: ["Ascent", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "WRX"],
	Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
	Toyota: [
		"4Runner",
		"86",
		"Avalon",
		"Camry",
		"Corolla",
		"Highlander",
		"Land Cruiser",
		"Prius",
		"RAV4",
		"Sequoia",
		"Sienna",
		"Tacoma",
		"Tundra",
		"Venza",
		"Yaris",
	],
	Volkswagen: ["Arteon", "Atlas", "Golf", "ID.4", "Jetta", "Passat", "Tiguan"],
	Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
};

// Generate years from 1980 to current year
const currentYear = new Date().getFullYear();
export const vehicleYears = Array.from({ length: currentYear - 1979 }, (_, i) => (currentYear - i).toString());

// Common vehicle colors
export const vehicleColors = [
	"Black",
	"White",
	"Silver",
	"Gray",
	"Red",
	"Blue",
	"Green",
	"Yellow",
	"Orange",
	"Brown",
	"Purple",
	"Gold",
	"Beige",
	"Burgundy",
	"Navy",
	"Bronze",
	"Champagne",
	"Copper",
	"Tan",
	"Turquoise",
];
